-- Substitui a categoria genérica "Serviços" por 15 categorias específicas
-- (2 níveis: categoria → subcategoria, sem 3º nível). Produtos que estavam
-- usando a categoria "Serviços" ficam sem categoria (category_id vira null
-- via on delete set null) — é esperado, o projeto ainda tem pouquíssimos
-- anúncios de serviço reais.

delete from public.categories where name = 'Serviços';

insert into public.categories (name, sort_order) values
  ('Casa e Manutenção', 23),
  ('Automotivo', 24),
  ('Tecnologia', 25),
  ('Limpeza', 26),
  ('Beleza e Estética', 27),
  ('Aulas e Educação', 28),
  ('Eventos', 29),
  ('Animais', 30),
  ('Jardinagem e Exterior', 31),
  ('Transporte e Entrega', 32),
  ('Serviços Profissionais', 33),
  ('Costura e Personalização', 34),
  ('Serviços Comerciais', 35),
  ('Esporte e Bem-estar', 36),
  ('Outros serviços', 37);

with cat as (select id, name from public.categories)
insert into public.subcategories (category_id, name, sort_order)
select cat.id, v.name, v.sort_order
from (values
  ('Casa e Manutenção','Encanador',1),
  ('Casa e Manutenção','Eletricista',2),
  ('Casa e Manutenção','Pedreiro',3),
  ('Casa e Manutenção','Pintor',4),
  ('Casa e Manutenção','Azulejista',5),
  ('Casa e Manutenção','Gesseiro',6),
  ('Casa e Manutenção','Marceneiro',7),
  ('Casa e Manutenção','Serralheiro',8),
  ('Casa e Manutenção','Vidraceiro',9),
  ('Casa e Manutenção','Instalador de ar-condicionado',10),
  ('Casa e Manutenção','Técnico de gás',11),
  ('Casa e Manutenção','Impermeabilização',12),
  ('Casa e Manutenção','Manutenção de telhado',13),
  ('Casa e Manutenção','Instalação de portas e janelas',14),
  ('Casa e Manutenção','Montador de móveis',15),

  ('Automotivo','Mecânico',1),
  ('Automotivo','Eletricista automotivo',2),
  ('Automotivo','Funileiro',3),
  ('Automotivo','Pintor automotivo',4),
  ('Automotivo','Martelinho de ouro',5),
  ('Automotivo','Lavagem automotiva',6),
  ('Automotivo','Polimento',7),
  ('Automotivo','Higienização',8),
  ('Automotivo','Borracharia',9),
  ('Automotivo','Guincho',10),
  ('Automotivo','Instalação de acessórios',11),
  ('Automotivo','Som automotivo',12),
  ('Automotivo','Insulfilm',13),

  ('Tecnologia','Técnico de informática',1),
  ('Tecnologia','Conserto de computador',2),
  ('Tecnologia','Conserto de celular',3),
  ('Tecnologia','Desenvolvimento de sites',4),
  ('Tecnologia','Desenvolvimento de aplicativos',5),
  ('Tecnologia','Designer',6),
  ('Tecnologia','Edição de vídeo',7),
  ('Tecnologia','Fotografia',8),
  ('Tecnologia','Suporte técnico',9),
  ('Tecnologia','Instalação de redes',10),
  ('Tecnologia','Manutenção de impressoras',11),

  ('Limpeza','Diarista',1),
  ('Limpeza','Faxineiro',2),
  ('Limpeza','Limpeza pós-obra',3),
  ('Limpeza','Limpeza de sofá',4),
  ('Limpeza','Limpeza de colchão',5),
  ('Limpeza','Limpeza de tapetes',6),
  ('Limpeza','Limpeza de piscina',7),
  ('Limpeza','Limpeza de caixa-d''água',8),
  ('Limpeza','Limpeza comercial',9),

  ('Beleza e Estética','Cabeleireiro',1),
  ('Beleza e Estética','Barbeiro',2),
  ('Beleza e Estética','Manicure',3),
  ('Beleza e Estética','Pedicure',4),
  ('Beleza e Estética','Maquiador',5),
  ('Beleza e Estética','Designer de sobrancelhas',6),
  ('Beleza e Estética','Trancista',7),
  ('Beleza e Estética','Esteticista',8),

  ('Aulas e Educação','Professor particular',1),
  ('Aulas e Educação','Reforço escolar',2),
  ('Aulas e Educação','Professor de idiomas',3),
  ('Aulas e Educação','Professor de música',4),
  ('Aulas e Educação','Aulas de informática',5),
  ('Aulas e Educação','Aulas de matemática',6),
  ('Aulas e Educação','Aulas preparatórias',7),

  ('Eventos','Fotógrafo',1),
  ('Eventos','Filmagem',2),
  ('Eventos','DJ',3),
  ('Eventos','Garçom',4),
  ('Eventos','Buffet',5),
  ('Eventos','Decoração',6),
  ('Eventos','Organização de eventos',7),
  ('Eventos','Som e iluminação',8),
  ('Eventos','Cerimonialista',9),

  ('Animais','Pet sitter',1),
  ('Animais','Dog walker',2),
  ('Animais','Banho e tosa',3),
  ('Animais','Adestrador',4),
  ('Animais','Cuidador de animais',5),
  ('Animais','Transporte de animais',6),

  ('Jardinagem e Exterior','Jardineiro',1),
  ('Jardinagem e Exterior','Paisagista',2),
  ('Jardinagem e Exterior','Poda de árvores',3),
  ('Jardinagem e Exterior','Corte de grama',4),
  ('Jardinagem e Exterior','Limpeza de terrenos',5),
  ('Jardinagem e Exterior','Manutenção de jardins',6),
  ('Jardinagem e Exterior','Piscineiro',7),

  ('Transporte e Entrega','Motoboy',1),
  ('Transporte e Entrega','Entregador',2),
  ('Transporte e Entrega','Motorista particular',3),
  ('Transporte e Entrega','Frete',4),
  ('Transporte e Entrega','Carreto',5),
  ('Transporte e Entrega','Mudança',6),
  ('Transporte e Entrega','Transporte de móveis',7),
  ('Transporte e Entrega','Transporte de pequenas cargas',8),

  ('Serviços Profissionais','Contador',1),
  ('Serviços Profissionais','Designer',2),
  ('Serviços Profissionais','Fotógrafo',3),
  ('Serviços Profissionais','Tradutor',4),
  ('Serviços Profissionais','Redator',5),
  ('Serviços Profissionais','Consultor',6),
  ('Serviços Profissionais','Marketing',7),
  ('Serviços Profissionais','Social media',8),
  ('Serviços Profissionais','Assistência administrativa',9),

  ('Costura e Personalização','Costureira',1),
  ('Costura e Personalização','Ajuste de roupas',2),
  ('Costura e Personalização','Consertos de roupas',3),
  ('Costura e Personalização','Bordado',4),
  ('Costura e Personalização','Personalização de camisetas',5),
  ('Costura e Personalização','Estamparia',6),
  ('Costura e Personalização','Confecção sob medida',7),

  ('Serviços Comerciais','Manutenção empresarial',1),
  ('Serviços Comerciais','Instalação de equipamentos',2),
  ('Serviços Comerciais','Segurança eletrônica',3),
  ('Serviços Comerciais','Câmeras',4),
  ('Serviços Comerciais','Alarmes',5),
  ('Serviços Comerciais','Controle de acesso',6),
  ('Serviços Comerciais','Comunicação visual',7),
  ('Serviços Comerciais','Letreiros',8),
  ('Serviços Comerciais','Fachadas',9),
  ('Serviços Comerciais','Manutenção de máquinas',10),

  ('Esporte e Bem-estar','Personal trainer',1),
  ('Esporte e Bem-estar','Professor de futebol',2),
  ('Esporte e Bem-estar','Professor de dança',3),
  ('Esporte e Bem-estar','Professor de artes marciais',4),
  ('Esporte e Bem-estar','Treinador esportivo',5),
  ('Esporte e Bem-estar','Yoga',6),
  ('Esporte e Bem-estar','Pilates',7),

  ('Outros serviços','Diversos',1)
) as v(category_name, name, sort_order)
join cat on cat.name = v.category_name;
